name: 'No Merge Commits Action'
description: 'Prevent merge commits in pull requests.'
author: 'John Paul E. Balandan, CPA'

branding:
  icon: 'git-merge'
  color: 'red'

inputs:
  token:
    description: Token to authenticate with GitHub, usually GITHUB_TOKEN
    required: true

runs:
  using: 'node20'
  main: 'dist/index.js'
