name: Check Dist

on:
  push:
    branches:
      - '1.x'
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  check-dist:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Cache dependencies
        id: cache-npm
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ github.job }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ github.job }}-npm-

      - name: List the state of dependencies
        if: steps.cache-npm.outputs.cache-hit != 'true'
        continue-on-error: true
        run: npm list

      - name: Install dependencies
        run: npm ci

      - name: Rebuild the dist/ directory
        run: |
          npm run build
          npm run package

      - name: Compare the expected and actual dist/ directories
        run: |
          if [[ -n "$(git status --porcelain 2>/dev/null)" ]]; then
            echo "Detected uncommitted changes after build. See status below:"
            git diff --text --ignore-space-at-eol
            exit 1
          fi
        id: diff

      - name: Upload expected version if different
        uses: actions/upload-artifact@v3
        if: ${{ failure() && steps.diff.conclusion == 'failure' }}
        with:
          name: dist
          path: dist/
          if-no-files-found: error
          retention-days: 1
