name: 'Continuous Integration'

on:
  pull_request:
  push:
    branches:
      - '1.x'

permissions:
  contents: read
  pull-requests: read

jobs:
  unit-test:
    name: Unit Test
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Cache dependencies
        id: cache-npm
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ github.job }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ github.job }}-npm-

      - name: List the state of dependencies
        if: steps.cache-npm.outputs.cache-hit != 'true'
        continue-on-error: true
        run: npm list

      - name: Install dependencies
        run: npm ci

      - name: Run all suites
        run: npm run all

  test-run:
    name: Run Live Test
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
