name: 'Continuous Integration'

on:
  pull_request:
  push:
    branches:
      - '1.x'

permissions:
  contents: read
  pull-requests: read

jobs:
  unit-test:
    name: Unit Test
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: npm ci
        env:
          TERM: xterm-256color

      - name: Run all suites
        run: npm run all
        env:
          TERM: xterm-256color

  test-run:
    name: Run Live Test
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
