name: 'Continuous Integration'

on:
  pull_request:
    branches:
      - '2.x'
  push:
    branches:
      - '2.x'

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-test:
    name: Unit Test
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Set Node 24
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: '24.x'

      - name: Cache dependencies
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ~/.npm
          key: ${{ github.job }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ github.job }}-npm-

      - name: Install dependencies
        run: npm ci

      - name: Run all suites
        run: npm run all

  integration-test:
    name: Integration Test
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Set Node 24
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: '24.x'

      - name: Cache dependencies
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ~/.npm
          key: ${{ github.job }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ github.job }}-npm-

      - name: Install dependencies
        run: npm ci

      - name: Always build latest distributable
        run: |
          npm run build
          npm run package

      - name: Run on PR
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
